active_robots: ['b_bot']
delta_actions: False
control_frequency: 50
camera_names: ['a_bot_outside_camera', 'b_bot_inside_camera']
max_force_torque: [50., 50., 50., 10., 10., 10.]

compliant_controller:
  p_gains: [0.035, 0.035, 0.035, 0.5, 0.5, 0.5]
  d_gains: [0, 0, 0, 0, 0, 0]
  error_scale: 0.8
  iterations: 1.0
  stiffness_limits:
    translation: [50, 1500]
    rotation: [10, 1000]

initial_configuration:
  b_bot: [0.9779, -1.4497, 1.6603, -1.7809, -1.5649, 0.9286] # joint configuration or named pose
  a_bot: [1.5665, -2.4674, 2.2339, -1.7811, -1.5622, -0.0075] # joint configuration or named pose
 
task_parameters:
  dataset_dir: '/root/osx-ur/dependencies/comp-act/datasets/b_bot_writing_v3'
  ckpt_dir: '/root/osx-ur/dependencies/rollouts/b_bot_writing_v3'
  num_episodes: 30
  episode_len: 3000
  camera_names: ['a_bot_outside_camera', 'b_bot_inside_camera']
  is_cartesian: True
  flip_gripper: True
  stiffness_configuration:
    modes:
      position: 
        low: [400, 400, 400.]
        normal: [800, 800, 800.]
        high: [1200, 1200, 1200.]
      rotation:
        low: [100, 100, 100.]
        normal: [150, 150, 150.]
        high: [300, 300, 300.]
    b_bot: ['low', 'normal'] # from normal to low when switching (inverted)
    # b_bot: ['normal', 'low'] # from normal to low when switching (inverted)
  stiffness_representation: 'diag' # or 'cholesky'
  orientation_representation: 'ortho6' # or 'axis_angle'
 
policy_parameters:
  bimanual: False
  action_dim: 16 # diag ortho6
  state_dim: 10 # ortho6
  ft_dim: 6
  policy_class: ACT
  hidden_dim: 512
  dim_feedforward: 3200
  lr_backbone: 1.0e-5
  backbone: 'resnet18'
  enc_layers: 4
  dec_layers: 7
  nheads: 8
  seed: 1
  kl_weight: 100
  batch_size: 24
  num_epochs: 200000
  chunk_size: 150
  num_queries: 150
  camera_names: ['a_bot_outside_camera', 'b_bot_inside_camera']
  temporal_agg: True
  include_ft: True
  ft_as_obs: False
  loss_type: l1
  include_stiffness: True
  action_space: 'cartesian'
  lr: 5.0e-5
  lr_scheduler: True
  grad_clip_norm: 10
  lr_warmup_steps: 2000
  num_steps_to_validate: 100
  validation_interval: 1000
  weight_decay: 1.0e-6
  validation_type: cross_validation
  # Define the keys and expected length of each array 
  training_data:
    observation_keys: [observation.eef_pos.position, observation.eef_pos.rotation_ortho6, observation.eef_pos.gripper]
    input_shapes:
      observation.eef_pos.position: [6]
      observation.eef_pos.rotation_ortho6: [12]
      observation.eef_pos.gripper: [2]
      observation.ft: [12]

    input_normalization_modes:
      observation.eef_pos.position: mean_std
      observation.eef_pos.rotation_ortho6: min_max
      observation.eef_pos.gripper: mean_std
      observation.ft: mean_std

    output_shapes: # order matters, so position and rotation first
      action.position: [3]
      action.rotation_ortho6: [6]
      action.gripper: [1]
      action.stiffness_diag: [6]

    output_normalization_modes:
      action.position: mean_std
      action.rotation_ortho6: min_max
      action.gripper: mean_std
      action.stiffness_diag: mean_std

vr_config:
  b_bot:
    controller:
      name: 'right_controller'
      frame_id: 'world'
      tracking_mode: 'controller_pose'

    robot:
      namespace: 'b_bot'
      base_frame: 'b_bot_base_link'
      end_effector_frame: 'b_bot_gripper_tip_link'
      ft_sensor_frame: 'b_bot_wrist_3_link'
      world_frame: 'world' # if defined, orient target pose around common world frame

    topics:
      wrench: '/b_bot/wrench'

    safety:
      play_area: [0.5, 0.5, 0.5, 45, 45, 90] # Units: meters for translation, degrees for orientation
      max_contact_force_torque: [50., 50., 50., 5., 5., 5.]
      scale_velocities: [1., 1., 1., 1., 1., 1.]
      scale_translation: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      max_delta_translation: 0.05 # m
      max_delta_rotation: [5.0, 5.0, 15.0] # degrees
