active_robots: ['a_bot', 'b_bot']
delta_actions: False
control_frequency: 50
camera_names: ['a_bot_inside_camera', 'b_bot_inside_camera', 'extra_camera']
max_force_torque: [50., 50., 50., 10., 10., 10.]

compliant_controller:
  p_gains: [0.035, 0.035, 0.035, 0.5, 0.5, 0.5]
  d_gains: [0, 0, 0, 0, 0, 0]
  error_scale: 0.8
  iterations: 1.0
  stiffness_limits:
    translation: [50, 1500]
    rotation: [10, 1000]

initial_configuration:
  b_bot: [1.5757, -2.1025, 1.8821, -1.6227, -1.7419, 0.6041] # joint configuration or named pose
  a_bot: [0.5616, -2.4457, 1.8921, -1.2245, -1.2846, -0.3727] # joint configuration or named pose
 
task_parameters:
  dataset_dir: 
    - '/root/osx-ur/dependencies/datasets/comp-act/bimanual_round_insertion_variable_v6'
    - '/root/osx-ur/dependencies/datasets/comp-act/bimanual_round_insertion_variable_v7'
  ckpt_dir: '/root/osx-ur/dependencies/rollouts/bimanual_round_insertion_variable_v7'
  num_episodes: 30
  episode_len: 1000
  camera_names: ['a_bot_inside_camera', 'b_bot_inside_camera', 'extra_camera']
  is_cartesian: True
  flip_gripper: True
  stiffness_configuration:
    modes:
      position: 
        low: [200, 200, 200.]
        normal: [800, 800, 800.]
        high: [1200, 1200, 1200.]
      rotation:
        low: [100, 100, 100.]
        normal: [150, 150, 150.]
        high: [300, 300, 300.]
    a_bot: ['normal', 'high'] # from normal to high when switching
    b_bot: ['normal', 'low'] # from normal to low when switching
  stiffness_representation: 'diag' # or 'cholesky'
  orientation_representation: 'ortho6' # or 'axis_angle'
 
policy_parameters:
  bimanual: True
  validation_type: cross_validation
  action_dim: 32 # diag ortho6
  state_dim: 20 # ortho6
  ft_dim: 12
  policy_class: ACT
  lr: 1.0e-5
  hidden_dim: 512
  dim_feedforward: 3200
  lr_backbone: 1.0e-5
  backbone: 'resnet18'
  enc_layers: 4
  dec_layers: 7
  nheads: 8
  seed: 1
  kl_weight: 100
  batch_size: 16
  num_epochs: 200000
  chunk_size: 100
  num_queries: 100
  camera_names: ['a_bot_inside_camera', 'b_bot_inside_camera', 'extra_camera']
  temporal_agg: True
  include_ft: True
  ft_as_obs: False
  loss_type: l1
  include_stiffness: True
  action_space: 'cartesian'
  # Define the keys and expected length of each array 
  training_data:
    observation_keys: [observation.eef_pos.position, observation.eef_pos.rotation_ortho6, observation.eef_pos.gripper]
    input_shapes:
      # observation.images.closeview: [3, 480, 640]
      # observation.images.robot1_eye_in_hand:  [3, 480, 640]
      observation.eef_pos.position: [6]
      observation.eef_pos.rotation_ortho6: [12]
      observation.eef_pos.gripper: [2]
      observation.ft: [12]

    input_normalization_modes:
      # observation.images.closeview: mean_std
      # observation.images.robot1_eye_in_hand: mean_std
      observation.eef_pos.position: mean_std
      observation.eef_pos.rotation_ortho6: min_max
      observation.eef_pos.gripper: mean_std
      observation.ft: mean_std

    output_shapes: # order matters, so position and rotation first
      action.position: [6]
      action.rotation_ortho6: [12]
      action.gripper: [2]
      action.stiffness_diag: [12]

    output_normalization_modes:
      action.position: mean_std
      action.rotation_ortho6: min_max
      action.gripper: mean_std
      action.stiffness_diag: mean_std

vr_config:
  a_bot:
    controller:
      name: 'left_controller'
      frame_id: 'world'
      tracking_mode: 'controller_pose'

    robot:
      namespace: 'a_bot'
      base_frame: 'a_bot_base_link'
      end_effector_frame: 'a_bot_gripper_tip_link'
      ft_sensor_frame: 'a_bot_wrist_3_link'
      world_frame: 'world' # if defined, rotate controller pose from world -> robot base

    topics:
      wrench: '/a_bot/wrench'

    safety:
      play_area: [0.5, 0.5, 0.5, 45, 45, 90] # Units: meters for translation, degrees for orientation
      max_contact_force_torque: [50., 50., 50., 5., 5., 5.]
      scale_velocities: [1., 1., 1., 1., 1., 1.]
      scale_translation: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      max_delta_translation: 0.05 # m
      max_delta_rotation: [5.0, 5.0, 15.0] # degrees

  b_bot:
    controller:
      name: 'right_controller'
      frame_id: 'world'
      tracking_mode: 'controller_pose'

    robot:
      namespace: 'b_bot'
      base_frame: 'b_bot_base_link'
      end_effector_frame: 'b_bot_gripper_tip_link'
      ft_sensor_frame: 'b_bot_wrist_3_link'
      world_frame: 'world' # if defined, orient target pose around common world frame

    topics:
      wrench: '/b_bot/wrench'

    safety:
      play_area: [0.5, 0.5, 0.5, 45, 45, 90] # Units: meters for translation, degrees for orientation
      max_contact_force_torque: [50., 50., 50., 5., 5., 5.]
      scale_velocities: [1., 1., 1., 1., 1., 1.]
      scale_translation: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      max_delta_translation: 0.05 # m
      max_delta_rotation: [5.0, 5.0, 15.0] # degrees
