delta_actions: False
control_frequency: 50
camera_names: ['a_bot_inside_camera', 'b_bot_inside_camera', 'extra_camera']
max_force_torque: [50., 50., 50., 5., 5., 5.]

compliant_controller:
  p_gains: [0.035, 0.035, 0.035, 1.5, 1.5, 1.5]
  d_gains: [0, 0, 0, 0, 0, 0]
  error_scale: 0.8
  iterations: 1.0
  stiffness_limits:
    translation: [100, 600]
    rotation: [10, 50]

initial_configuration:
  b_bot: 'home' # joint configuration or named pose
  a_bot: 'home' # joint configuration or named pose

task_parameters: 
  dataset_dir: '/root/osx-ur/datasets/dual_arm_simple'
  num_episodes: 50
  episode_len: 1000
  camera_names: [] #['wrist_camera', 'extra_camera']
