# main loop frequency [Hz] (should be as fast as F/T sensor publish frequency)
loop_rate: 500.0

# waiting time after moving to each pose before taking F/T measurements
wait_time: 3.0

# Name of the moveit group
moveit_group_name: 'b_bot'

# Name of the calib file
calib_file_name: 'b_bot_ft_calib_data.yaml'

# Name of the directory
calib_file_dir: '/root/osx-ur/catkin_ws/src/osx_scene_description/config/payload'

# Name of file to store measurements
meas_file_name: 'b_bot_ft_calib_meas.txt'

# Name of the directory
meas_file_dir: '/root/osx-ur/catkin_ws/src/osx_scene_description/config/payload'

# don't execute random poses
random_poses: false

# number of random poses
number_random_poses: 0

# the poses to which to move the arm in order to calibrate the F/T sensor
# format: [x y z r p y]  in meters, radians
# poses_frame_id sets the frame at which the poses are expressed
poses_frame_id: 'b_bot_base_link'

pose_type: 'joint' # 'cartesian'

poses:
  - [1.5699, -2.1, 1.4, -0.8499, -1.57, 0.0001]
  - [1.5683, -2.0995, 1.4009, -0.5011, -1.5694, -0.001]
  - [1.5683, -2.0995, 1.4009, -0.5011, -1.5694, 1.5701]
  - [2.9868, -2.1, 1.4001, -0.3278, -1.5701, -0.0104]
  - [-0.0751, -2.0993, 1.4018, -0.5016, -1.5687, -0.0011]
  - [1.5692, -2.0999, 1.4021, -1.1922, -1.5695, 0.0011]
  - [1.5692, -2.0999, 1.4021, -1.1922, -1.5695, 1.5711]
  - [1.5705, -2.3196, 2.0292, -2.8505, -1.5713, 0.0002]
  - [1.5806, -2.3076, 2.0066, -2.8519, -0.0549, 0.0107]
  - [1.5797, -2.3066, 2.0062, -2.8513, 1.5844, 0.0]
  - [1.5797, -2.3066, 2.0062, -2.8513, 1.5844, 1.5703]
  - [1.5705, -2.3196, 2.0292, -2.8505, -1.5713, 1.5702]
  - [1.5796, -2.3065, 2.0062, -2.8513, -3.0059, 0.0103]
  - [1.5796, -2.3065, 2.0062, -2.8513, -3.0059, 1.5703]
  - [1.5699, -2.1, 1.4, -0.8499, -1.57, 0.0001]
