# ================== Dataset Configuration ==================
dataset:
  repo_id: test_wipe_osx
  task: "Pick and place the object"
  root: /root/osx-ur/dependencies/comet/data # null = lerobot default (~/.cache/huggingface/lerobot)
  overwrite: false
  fps: 50
  num_episodes: 50
  episode_time_s: 60.0
  reset_time_s: 10.0
  robot_type: ur5e

# ================== Camera Configuration ==================
cameras:
  front_camera:
    height: 480
    width: 640
    channels: 3
  wrist_camera:
    height: 480
    width: 640
    channels: 3

# ================== Observation (state) features ==================
# key: feature name used in the dataset
# value: list of ints representing the shape
states:
  observation.qpos: [6]
  observation.qvel: [6]
  observation.eef.position: [3]
  observation.eef.linear_velocity: [3]
  observation.eef.angular_velocity: [3]
  observation.eef.rotation_ortho6: [6]
  observation.eef.rotation_axis_angle: [3]
  observation.ft: [6]

# ================== Action features ==================
actions:
  action.joint: [6]
  action.position: [3]
  action.rotation_ortho6: [6]
  action.rotation_axis_angle: [3]
  action.stiffness_diag: [6]
  action.delta_position: [3]
  action.delta_rotation: [3]

# ================== Image Writer ==================
image_writer:
  num_processes: 0
  threads_per_camera: 4


# ================== Controller Configuration ==================
controller:
  type: "fdcc"
  base_link: "base_link"
  ee_link: "tool0"
  use_velocity_interface: false
  reset_time: 2.0
  actions_as_deltas: false
  # FDCC parameters
  mode: "spring-mass-damper" # "parallel"
  p_gains: [0.035, 0.035, 0.035, 0.1, 0.1, 0.1]
  d_gains: [0, 0, 0, 0, 0, 0]
  selection_matrix: [1, 1, 1, 1, 1, 1]
  error_scale: 0.8
  iterations: 1.0
  stiffness: 1500

safety_parameters:
  max_force_torque: [70, 10]
  max_delta_translation: 0.05
  max_delta_rotation: [5.0, 5.0, 15.0]
  workspace_range:
    x: [ 0.0, 0.90]
    y: [-0.9, 0.90]
    z: [ -0.0, 0.80]
  stiffness_limits:
    translation: [50, 1500]
    rotation: [10, 1000]

init_qpos: [0.4289, -1.229, 1.461, -1.7436, -1.4361, 0.1035]
